name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     AZURE_ACR: andoniacr.azurecr.io
    steps:
      - uses: actions/checkout@v3
      
      - uses: azure/docker-login@v1
        with:
          login-server: ${AZURE_ACR}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push 
        working-directory: ./src/web
        run: |
          docker build . -t ${AZURE_ACR}/web:${{ github.sha }} 
          docker push ${AZURE_ACR}/web:${{ github.sha }}

         
