name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    
env:
  image_name: "andoniacr.azurecr.io/web:${{ github.sha }}"
  app_name: "web"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: azure/docker-login@v1
        with:
          login-server: "andoniacr.azurecr.io"
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push 
        working-directory: ./src/web
        run: |
          docker build . -t  $image_name
          docker push  $image_name
          
  deploy:
      name: 'Terraform'
      needs: build
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        TERRAFORM_VERSION: "1.3.1"
        TERRFAORM_WORKING_DIR : "./deploy/aca_web"
        feature_name: ${{ github.event.pull_request.title }}
        
      runs-on: ubuntu-latest
      environment: production

      # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
      defaults:
        run:
          shell: bash

      steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version:  $TERRAFORM_VERSION
          tf_actions_subcommand: 'init'
          tf_actions_working_dir:  $TERRFAORM_WORKING_DIR
          
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version:  $TERRAFORM_VERSION
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir:  $TERRFAORM_WORKING_DIR

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version:  $TERRAFORM_VERSION
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: $TERRFAORM_WORKING_DIR

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version:   $TERRAFORM_VERSION
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir:  $TERRFAORM_WORKING_DIR

       
         
