name: Pull request destroy environment

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  
  destroy:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      feature_name: pr-${{ github.event.pull_request.number }}
      
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        working-directory: './deploy/1_aca_web'
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="key=${{ env.feature_name }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Destroy
        id: apply
        run:  terraform destroy --auto-approve
        env:
          TF_VAR_image_name: ${{ env.image_name }}
          TF_VAR_app_name: ${{ env.app_name }}
          TF_VAR_feature_name: ${{ env.feature_name }}
